settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: golang-webapi-demo
  path: .
  commands: 
    build:
      status: true
      method: go build -o /tmp/app
    run:
      status: true
      method: /tmp/app
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    - mocks
    