name: CI

on:
  push:
    branches:    
    - master
    - main
    - 'release/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret1234!
          MYSQL_DATABASE: golang_webapi_demo_test

    container:
      image: golang:1.16
      env:
        MYSQL_TEST_URL: 'root:secret1234!@tcp(mysql:3306)/golang_webapi_demo_test?charset=utf8&parseTime=True&loc=Local'

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - uses: actions/checkout@v2

    - name: Install DB migration tool
      run: go get bitbucket.org/liamstask/goose/cmd/goose

    - name: Setup DB Schema
      run: goose -env test up

    - name: Run Go Test
      run: go test -v -race -cover  ./... -parallel 4
